from einops import rearrange
import mujoco
import numpy as np


class DataLoader:
    """
    This class loads the recording from file.
    """

    def __init__(self, name, mujoco_model="model/scene.xml"):
        """
        name: Name of the recording, only the name, no path, no file ending
        mujoco_model: Path to the mujoco model
        """
        # Setup mujoco
        self.model_name = mujoco_model
        self.name = name
        self.model = mujoco.MjModel.from_xml_path(mujoco_model)

        # Load up the data
        # Hint: The output folder will be generated by the Go2Recorder in the project root!
        data = np.load(
            f"output/{name}.npy"
        )  # storage.npy has the fields: state, timestamp and dt
        
        # Load time differences
        self.dt = data["dt"]
        
        # Duration
        self.duration = int(data['timestamp'][-1] - data['timestamp'][0])
        
        state = data["state"]
        state = rearrange(
            state,
            "(frame dim) -> frame dim",
            dim=(self.model.nq + self.model.nv + self.model.nu + 8 * self.model.nu + 4),
        )
        # 8 * are the extra fields for each joint and + 4 covers the recorded foot force

        nq = self.model.nq
        nv = self.model.nv
        nu = self.model.nu

        # Indices
        i = 0
        self.qpos = state[:, i : i + nq]
        i += nq
        self.qvel = state[:, i : i + nv]
        i += nv
        self.ctrl = state[:, i : i + nu]
        i += nu

        # From low cmd
        self.q = state[:, i : i + nu]
        i += nu
        self.dq = state[:, i : i + nu]
        i += nu
        self.tau = state[:, i : i + nu]
        i += nu
        self.kp = state[:, i : i + nu]
        i += nu
        self.kd = state[:, i : i + nu]
        i += nu

        # From low state
        self.tau_est = state[:, i : i + nu]
        i += nu
        self.q_raw = state[:, i : i + nu]
        i += nu
        self.dq_raw = state[:, i : i + nu]
        i += nu
        
        # Foot force (4)
        self.foot_force = state[:, i : i + 4]

        self.compact_states = rearrange(
            state[:, : self.model.nq + self.model.nv], "frame posvel -> 1 frame posvel"
        )
        self.compact_actions = rearrange(
            state[:, self.model.nq + self.model.nv :], "frame ctrl -> 1 frame ctrl"
        )

    def get_states(self):
        """
        Returns the states, i. e.:
        qpos (19)
        qvel (18)

        Shape: (batch, 37)
        """
        return self.compact_states

    def get_qpos(self):
        """
        Returns qpos (19)

        Shape: (batch, 19)
        """

        return self.qpos

    def get_qvel(self):
        """
        Returns qvel (18)

        Shape: (batch, 18)
        """
        return self.qvel

    def get_ctrl(self):
        """
        Returns the actions, i .e., as goal torque:
        tau + kp * (q - q_raw) + kd * (dq - dq_raw)

        Where q_raw and dq_raw are the estimations from low state.

        Shape: (batch, 12)
        """
        return self.ctrl

    def get_low_state_meta(self):
        """
        Returns the meta for low state, i. e.: tau_est (12), q_raw (12), dq_raw (12)

        Shape: (batch, 36)
        """

        return self.tau_est, self.q_raw, self.dq_raw

    def get_low_cmd_meta(self):
        """
        Returns the meta for low cmd, i. e.: q (12), dq (12), tau (12), kp (12), kd (12)

        Shape: (batch, 60)
        """
        return self.q, self.dq, self.tau, self.kp, self.kd

    def get_mj_model(self):
        """
        Returns the loaded MuJoco model
        """
        return self.model

    def get_dt(self):
        """
        Returns the time differences between each state

        Shape: (batch, )
        """
        return self.dt

    def get_duration(self):
        """
        Returns the duration in seconds.
        """
        return self.duration
    
    def get_foot_force(self):
        """
        Returns the foot forces (4)
        Shape: (batch, 4)
        """
        return self.foot_force
    
    def print_debug(self):
        print("------------------------------------------------------")
        print("File name:", self.name)
        print("Model name:", self.model_name)
        print(f"Clip duration: {self.get_duration()}s")
        print("qpos, qvel, ctrl shape:", self.get_qpos().shape, self.get_qvel().shape, self.get_ctrl().shape)
        print("Mean dt:", np.mean(self.get_dt()), "STD dt:", np.std(self.get_dt()))
        print("------------------------------------------------------")