import numpy as np
from einops import rearrange
import mujoco
import mediapy as media
from tqdm import tqdm
import matplotlib.pyplot as plt

# Setup mujoco
model = mujoco.MjModel.from_xml_path('model/scene.xml')
mj_data = mujoco.MjData(model)
# enable joint visualization option:
scene_option = mujoco.MjvOption()
scene_option.flags[mujoco.mjtVisFlag.mjVIS_JOINT] = True

# Load up the data
# Hint: The output folder will be generated by the Go2Recorder in the project root!
data = np.load('output/storage.npy') #storage.npy has the fields: state, timestamp and dt
state = data['state']
state = rearrange(state, '(frame dim) -> frame dim', dim=(model.nq + model.nv + model.nu + 8 * model.nu))

print("after tensor transform", state.shape)

# # Split into qpos, qvel, ctrl using model dimensions for robustness
nq = model.nq
nv = model.nv
nu = model.nu

# Indices
i = 0
qpos = state[:, i : i + nq]; i += nq
qvel = state[:, i : i + nv]; i += nv
ctrl = state[:, i : i + nu]; i += nu

# From low cmd
q      = state[:, i : i + nu]; i += nu
dq     = state[:, i : i + nu]; i += nu
tau    = state[:, i : i + nu]; i += nu
kp     = state[:, i : i + nu]; i += nu
kd     = state[:, i : i + nu]; i += nu

# From low state
tau_est = state[:, i : i + nu]; i += nu
q_raw   = state[:, i : i + nu]; i += nu
dq_raw  = state[:, i : i + nu]; i += nu

print(qpos.shape, qvel.shape, ctrl.shape)

state_array = rearrange(state[:, :model.nq+model.nv], 'frame posvel -> 1 frame posvel')
action_array = rearrange(state[:, model.nq+model.nv:], 'frame ctrl -> 1 frame ctrl')

print("State array shape", (state_array.shape))
print("Action array shape", (action_array.shape))

# Hint: See this time steps as a reference, but do not rely on them, as they are inaccurate.
# # Time management
# dt_arr = data['dt']
# print("dt mean and var:", dt_arr.mean(), dt_arr.var())

# assert np.all(dt_arr > 0)
# dt = dt_arr.mean()

# print("qvel shape", qvel.shape)

camera = mujoco.MjvCamera()

body_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "base_link")
if body_id != -1:
    camera.type = mujoco.mjtCamera.mjCAMERA_TRACKING
    camera.trackbodyid = body_id
    camera.distance = 3.0

# Render video
duration = int(data['timestamp'][-1] - data['timestamp'][0])
framerate = 60
time = 0

frames = []
mujoco.mj_resetData(model, mj_data)
with mujoco.Renderer(model) as renderer:
    for pos, vel, ctrl in tqdm(zip(qpos, qvel, ctrl), total=len(qpos), desc="Rendering frames"):
        mj_data.qpos[:] = pos
        mj_data.qvel[:] = vel
        mj_data.ctrl[:] = ctrl
        
        mujoco.mj_forward(model, mj_data)
        
        time = time + 0.01
        
        if len(frames) < time * framerate:
            renderer.update_scene(mj_data, camera=camera)
            pixels = renderer.render()
            frames.append(pixels)

media.write_video(f"renderer/trajectory.mp4", frames, fps=framerate)